var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/error/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__6e11e2a9._.js")
R.c("server/chunks/ssr/ccf52_next_dist_10785623._.js")
R.c("server/chunks/ssr/ccf52_next_dist_f596b582._.js")
R.c("server/chunks/ssr/ccf52_83bbe7de._.js")
R.c("server/chunks/ssr/botchat-pro_app_283d2fda._.js")
R.c("server/chunks/ssr/[root-of-the-server]__19fd73f0._.js")
R.c("server/chunks/ssr/ccf52_next_dist_client_components_f021821b._.js")
R.c("server/chunks/ssr/ccf52_next_dist_client_components_builtin_forbidden_e6c6aa98.js")
R.c("server/chunks/ssr/ccf52_next_dist_client_components_builtin_unauthorized_8f630c9f.js")
R.c("server/chunks/ssr/ccf52_next_dist_client_components_builtin_global-error_8be8c87c.js")
R.c("server/chunks/ssr/botchat-pro_app_error_layout_tsx_de7d8dc1._.js")
R.c("server/chunks/ssr/[root-of-the-server]__fde3fe3b._.js")
R.c("server/chunks/ssr/botchat-pro_398c8b64._.js")
R.c("server/chunks/ssr/botchat-pro_6e34f75f._.js")
R.m(55581)
R.m(28155)
module.exports=R.m(28155).exports
